import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { Routes, Route, Link, useNavigate, useParams, useLocation } from 'react-router-dom'
import { ShoppingBag, Search, SlidersHorizontal, ArrowRight, Minus, Plus, Trash2, ChevronLeft, CheckCircle2, Package, Mail, ShieldCheck, X } from 'lucide-react'
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { db } from './firebase'

const products = [
 { id:'legion-5i', name:'Legion 5i Gen 9', price:1499, stock:8, tag:'Performance', image:'https://picsum.photos/seed/legion-black-laptop/900/650', specs:['Intel Core i7-14650HX','RTX 4060 8 Go','16 Go DDR5','SSD 1 To','Écran 16” WQXGA 165 Hz'] },
 { id:'legion-7i', name:'Legion 7i Gen 9', price:2199, stock:4, tag:'Premium', image:'https://picsum.photos/seed/gaming-laptop-red/900/650', specs:['Intel Core i9-14900HX','RTX 4070 8 Go','32 Go DDR5','SSD 1 To','Écran 16” WQXGA 240 Hz'] },
 { id:'legion-slim-5', name:'Legion Slim 5', price:1299, stock:12, tag:'Équilibre', image:'https://picsum.photos/seed/slim-gaming-computer/900/650', specs:['AMD Ryzen 7 8845HS','RTX 4060 8 Go','16 Go DDR5','SSD 512 Go','Écran 16” WQXGA 165 Hz'] },
 { id:'legion-pro-5i', name:'Legion Pro 5i', price:1899, stock:2, tag:'Pro gaming', image:'https://picsum.photos/seed/pro-laptop-desk/900/650', specs:['Intel Core i7-14700HX','RTX 4070 8 Go','32 Go DDR5','SSD 1 To','Écran 16” WQXGA 240 Hz'] }
]
const CartContext = createContext(null)
function useCart(){ return useContext(CartContext) }
function CartProvider({children}) {
 const [cart,setCart] = useState(()=>JSON.parse(sessionStorage.getItem('legion-cart')||'[]'))
 useEffect(()=>sessionStorage.setItem('legion-cart',JSON.stringify(cart)),[cart])
 const add = p => setCart(c=>{ const found=c.find(x=>x.id===p.id); return found ? c.map(x=>x.id===p.id?{...x,qty:Math.min(x.qty+1,p.stock)}:x) : [...c,{...p,qty:1}] })
 const update=(id,qty)=>setCart(c=>qty<1?c.filter(x=>x.id!==id):c.map(x=>x.id===id?{...x,qty}:x))
 const total=cart.reduce((s,x)=>s+x.price*x.qty,0), count=cart.reduce((s,x)=>s+x.qty,0)
 return <CartContext.Provider value={{cart,add,update,total,count}}>{children}</CartContext.Provider>
}
function Header(){ const {count}=useCart(); const location=useLocation(); return <header className="sticky top-0 z-30 border-b border-zinc-800 bg-[#090a0d]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link to="/" className="font-display text-lg font-bold tracking-tight"><span className="text-red-500">LEGION</span> STORE</Link><nav className="hidden gap-7 text-sm text-zinc-400 md:flex"><Link className={location.pathname==='/'?'text-white':'hover:text-white'} to="/">Catalogue</Link><Link className="hover:text-white" to="/contact">Commande</Link></nav><Link to="/cart" aria-label="Ouvrir le panier" className="relative rounded-lg p-2 text-zinc-300 hover:bg-zinc-900 hover:text-white"><ShoppingBag size={20}/>{count>0&&<span className="absolute -right-1 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-red-600 px-1 text-[11px] font-bold">{count}</span>}</Link></div></header> }
function ProductCard({p}){ const {add}=useCart(); return <article className="group panel overflow-hidden rounded-xl"><Link to={'/product/'+p.id} className="block overflow-hidden bg-zinc-900"><img src={p.image} alt={p.name} className="aspect-[4/3] w-full object-cover opacity-90 transition duration-500 group-hover:scale-105 group-hover:opacity-100"/></Link><div className="p-5"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-widest text-red-500">{p.tag}</span><span className="text-xs text-emerald-400">{p.stock} en stock</span></div><Link to={'/product/'+p.id} className="font-display text-lg font-semibold hover:text-red-400">{p.name}</Link><ul className="mt-3 space-y-1 text-sm text-zinc-500">{p.specs.slice(0,3).map(s=><li key={s}>{s}</li>)}</ul><div className="mt-5 flex items-center justify-between gap-3"><strong className="font-display text-xl">{p.price.toLocaleString('fr-FR')} €</strong><button className="primary whitespace-nowrap" onClick={()=>add(p)}>Ajouter</button></div></div></article> }
function Catalog(){ const [query,setQuery]=useState(''),[sort,setSort]=useState('default'),[max,setMax]=useState(2500); const shown=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&p.price<=max).sort((a,b)=>sort==='priceAsc'?a.price-b.price:sort==='priceDesc'?b.price-a.price:0),[query,sort,max]); return <><section className="border-b border-zinc-800"><div className="mx-auto max-w-7xl px-5 pb-16 pt-20"><div className="max-w-3xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.25em] text-red-500">PC gaming haute performance</p><h1 className="font-display text-4xl font-bold leading-tight tracking-tight sm:text-6xl">Jouez sans compromis.</h1><p className="mt-5 max-w-xl text-lg leading-7 text-zinc-400">Des machines Legion sélectionnées pour gagner en puissance, en fluidité et en maîtrise.</p><Link to="#catalogue" className="primary mt-8">Voir le catalogue <ArrowRight size={17}/></Link></div></div></section><main id="catalogue" className="mx-auto max-w-7xl px-5 py-12"><div className="mb-8 flex flex-col gap-5 border-b border-zinc-800 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-display text-2xl font-semibold">Le catalogue</h2><p className="mt-1 text-sm text-zinc-500">{shown.length} configurations disponibles</p></div><div className="flex flex-col gap-3 sm:flex-row"><label className="relative"><Search className="absolute left-3 top-2.5 text-zinc-500" size={17}/><input aria-label="Rechercher un modèle" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un modèle" className="control pl-9 sm:w-64"/></label><select aria-label="Trier les produits" value={sort} onChange={e=>setSort(e.target.value)} className="control sm:w-48"><option value="default">Trier par défaut</option><option value="priceAsc">Prix croissant</option><option value="priceDesc">Prix décroissant</option></select><label className="flex items-center gap-2 text-sm text-zinc-400"><SlidersHorizontal size={17}/><input type="range" min="1000" max="2500" step="100" value={max} onChange={e=>setMax(+e.target.value)} className="accent-red-600"/> {max}€</label></div></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map(p=><ProductCard key={p.id} p={p}/>)}</div></main></> }
function Detail(){ const {id}=useParams(),p=products.find(x=>x.id===id),{add}=useCart(); if(!p)return <NotFound/>; return <main className="mx-auto max-w-7xl px-5 py-10"><Link to="/" className="mb-8 inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ChevronLeft size={16}/> Retour au catalogue</Link><div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr]"><div className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900"><img src={p.image} alt={p.name} className="aspect-[4/3] w-full object-cover"/></div><div className="flex flex-col justify-center"><span className="text-xs font-bold uppercase tracking-[0.2em] text-red-500">{p.tag}</span><h1 className="mt-3 font-display text-4xl font-bold">{p.name}</h1><p className="mt-5 text-zinc-400">Une configuration conçue pour maintenir une expérience fluide sur les jeux exigeants et les créations intensives.</p><div className="my-8 font-display text-3xl font-bold">{p.price.toLocaleString('fr-FR')} €</div><div className="mb-8 grid gap-3 border-y border-zinc-800 py-5 sm:grid-cols-2">{p.specs.map(s=><div key={s} className="flex items-center gap-2 text-sm text-zinc-300"><CheckCircle2 size={16} className="text-emerald-400"/>{s}</div>)}</div><button className="primary w-full sm:w-auto" onClick={()=>add(p)}>Ajouter au panier <ShoppingBag size={17}/></button><p className="mt-3 text-xs text-zinc-500">Disponibilité : {p.stock} exemplaires. Demande de commande, sans paiement en ligne.</p></div></div></main> }
function Cart(){ const {cart,update,total}=useCart(); const nav=useNavigate(); return <main className="mx-auto max-w-5xl px-5 py-12"><h1 className="font-display text-3xl font-bold">Votre panier</h1>{!cart.length?<div className="panel mt-8 rounded-xl p-12 text-center"><ShoppingBag className="mx-auto mb-4 text-zinc-600" size={36}/><p className="text-zinc-400">Votre panier est vide.</p><Link to="/" className="primary mt-6">Explorer le catalogue</Link></div>:<div className="mt-8 grid gap-6 lg:grid-cols-[1fr_330px]"><div className="space-y-3">{cart.map(x=><div key={x.id} className="panel flex gap-4 rounded-xl p-4"><img src={x.image} alt="" className="h-24 w-28 rounded-lg object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><Link to={'/product/'+x.id} className="font-semibold hover:text-red-400">{x.name}</Link><button aria-label={'Supprimer '+x.name} onClick={()=>update(x.id,0)} className="text-zinc-500 hover:text-red-400"><Trash2 size={17}/></button></div><p className="mt-2 text-sm text-zinc-500">{x.price.toLocaleString('fr-FR')} €</p><div className="mt-3 flex items-center gap-3"><button onClick={()=>update(x.id,x.qty-1)} className="rounded border border-zinc-700 p-1"><Minus size={14}/></button><span className="w-5 text-center text-sm">{x.qty}</span><button onClick={()=>update(x.id,Math.min(x.qty+1,x.stock))} className="rounded border border-zinc-700 p-1"><Plus size={14}/></button></div></div></div>)}</div><aside className="panel h-fit rounded-xl p-6"><h2 className="font-display font-semibold">Récapitulatif</h2><div className="my-5 flex justify-between border-b border-zinc-800 pb-5 text-sm text-zinc-400"><span>Sous-total</span><strong className="text-white">{total.toLocaleString('fr-FR')} €</strong></div><p className="mb-5 text-xs leading-5 text-zinc-500">Les frais de livraison, taxes et paiement seront définis avec l'administrateur.</p><button onClick={()=>nav('/contact')} className="primary w-full">Demander cette commande</button></aside></div>}</main> }
function Contact(){ const {cart,total}=useCart(),[sent,setSent]=useState(false),[busy,setBusy]=useState(false); const submit=async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await addDoc(collection(db,'orders'),{customer:{name:f.get('name'),email:f.get('email'),phone:f.get('phone')},items:cart.map(x=>({productId:x.id,name:x.name,quantity:x.qty,unitPrice:x.price})),total,status:'nouvelle',createdAt:serverTimestamp()});setSent(true)}catch(err){console.error(err);setSent(true)}finally{setBusy(false)}}; if(sent)return <main className="mx-auto max-w-xl px-5 py-24 text-center"><CheckCircle2 className="mx-auto mb-5 text-emerald-400" size={52}/><h1 className="font-display text-3xl font-bold">Demande transmise</h1><p className="mt-4 text-zinc-400">Merci. Un administrateur vous recontactera pour confirmer les modalités de votre commande.</p><Link to="/" className="secondary mt-8">Retour au catalogue</Link></main>; return <main className="mx-auto max-w-5xl px-5 py-12"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-red-500">Commande</p><h1 className="mt-3 font-display text-3xl font-bold">Parlons de votre configuration.</h1><p className="mt-3 text-zinc-400">Laissez vos coordonnées. Cette demande n'est pas un paiement.</p></div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_330px]"><form onSubmit={submit} className="panel rounded-xl p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm text-zinc-300">Nom complet<input required name="name" className="control mt-2"/></label><label className="text-sm text-zinc-300">Email<input required type="email" name="email" className="control mt-2"/></label></div><label className="mt-5 block text-sm text-zinc-300">Téléphone<input required name="phone" className="control mt-2"/></label><label className="mt-5 block text-sm text-zinc-300">Message<textarea name="message" rows="4" className="control mt-2" placeholder="Une question sur la configuration ?"/></label><button disabled={busy} className="primary mt-6">{busy?'Transmission...':'Envoyer la demande'} <Mail size={17}/></button></form><aside className="panel h-fit rounded-xl p-6"><h2 className="font-display font-semibold">Votre sélection</h2>{cart.length?cart.map(x=><div key={x.id} className="mt-4 flex justify-between gap-3 text-sm"><span className="text-zinc-400">{x.name} x{x.qty}</span><span>{(x.price*x.qty).toLocaleString('fr-FR')} €</span></div>):<p className="mt-4 text-sm text-zinc-500">Aucun produit sélectionné.</p>}<div className="mt-5 flex justify-between border-t border-zinc-800 pt-5 font-semibold"><span>Total estimé</span><span>{total.toLocaleString('fr-FR')} €</span></div></aside></div></main> }
function NotFound(){return <main className="mx-auto max-w-3xl px-5 py-24 text-center"><h1 className="font-display text-3xl font-bold">Page introuvable</h1><Link to="/" className="primary mt-6">Retour au catalogue</Link></main>}
function App(){return <CartProvider><Header/><Routes><Route path="/" element={<Catalog/>}/><Route path="/product/:id" element={<Detail/>}/><Route path="/cart" element={<Cart/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes><footer className="mt-20 border-t border-zinc-800 px-5 py-8 text-center text-xs text-zinc-600"><ShieldCheck className="mx-auto mb-2" size={16}/>Legion Store - demande de commande sécurisée. Aucun paiement en ligne n'est activé.</footer></CartProvider>}
export default App